#!/bin/tcsh
setenv PATH /home/ahadiashar/sw-rhel/bin:/home/ahadiashar/sw/bin:/usr/local/bin:/bin:/usr/bin:/usr/sbin/tools/usr/bin
setenv METAWARE_ROOT /proj/firmware/ARC/MetaWare

#build c-lightxw
setenv P4CLIENT bvlab-ahadiashar-c-lightxw
cd /nfs/home/ahadiashar/p4/c-lightxw/lightx/a1
p4 sync
make clean && make

#build c-lxww
setenv P4CLIENT bvlab-ahadiashar-c-lxww
cd /nfs/home/ahadiashar/p4/c-lxww/lightxw/a0
p4 sync
make clean && make sdk
cd sdk
source localsdk.tsh
make -C test_apps/bringup
make -C test_apps/pbench
